#!/bin/bash
if [ ! -n $1 ];
then 
    echo "No parameter passed."
else
    cd=$0
    script_path=$(dirname $(readlink -f $0))
    id=$( python $script_path/main.py $@ | dmenu |awk '{print $1}')
    video="https://youtube.com/watch?v=$id"
    echo "Playing video ..."
    mpv $video
fi
